plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs

# WORKAROUND: PnP doesn't support node's "imports" field https://github.com/yarnpkg/berry/issues/3843
nodeLinker: node-modules